# Generated by Django 3.2.7 on 2021-10-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
