# Generated by Django 3.2.7 on 2021-10-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='shop_item',
        ),
    ]
