# Generated by Django 3.2.7 on 2021-10-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_item_cat_gar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cat_gar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories'),
        ),
    ]
