# Generated by Django 3.2.7 on 2021-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_item_cat_gar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cat_gar',
            field=models.CharField(max_length=20),
        ),
    ]
